<?php
/**
* Category widget
*
* .category-description.fng.haut .content.catalog-category.category-list ul
* .content.catalog-category.category-list li.level-item0
*
* @var $block Emizentech\categorywidget\Block\Widget\Showcategories
*/

$title = $block->getTitle() ? __($block->getTitle()) : 'Categories';
$level = $this->getData('level');
$title_display = $block->getData('title_display');
$category_title_display = $block->getData('category_title_display');
$category_image_display = $block->getData('category_image_display');

?>
<div class="widget showcategories">
<?php
	if ($title_display=='yes'): ?>
<div class="block-title">
    <strong role="heading" aria-level="2"><h3><?php /* @escapeNotVerified */
            echo $title; ?></h3></strong>
</div>
<?php
  endif;
?>
<?php $collection = $block->getCategoryCollection(); ?>
<nav class="navigation" role="navigation">
<div class="block subnav">
	<div class="content catalog-category category-list">
    <?php
    foreach ($collection as $category):
        if (!$category->getIsActive()) {
            continue;
        }
        ?>
        <ul>
						<?php
							if ($category_image_display=='yes'): ?>
								<img src="<?php echo $category->getImageUrl(); ?>">
						<?php
							endif;
						?>
            <li>
								<?php
									if ($category_title_display=='yes'): ?>
										<li class="level-top0 cat-level<?php echo $category->getLevel() ?>"><a class="level-top0" href="<?php echo $category->getUrl($category) ?>"><?php echo $category->getName() ?></a></li>
								<?php
									endif;
								?>
                <?php

                if ($childrenCategories = $category->getChildrenCategories()): ?>

                <?php
                foreach ($childrenCategories as $childrenCategory):
                    if (!$childrenCategory->getIsActive()) {
                        continue;
                    }

                    ?>
                    <li class="level-item0 cat-level<?php echo $childrenCategory->getLevel() ?>">
                        <a class="level-item0" href="<?php echo $childrenCategory->getUrl($category); ?>"><?php echo $childrenCategory->getName() ?></a>
                    </li>
										<?php
												if ($level>0)
												{
													$block->renderCategoriesTree($childrenCategory, $childrenCategory->getId(), $level, true);
												}
										?>
								<?php
								//
                endforeach;
                ?>
            </li>
            <?php
            endif;
            ?>
        </ul>
        <?php
    endforeach;
    ?>
	</div>
</div>
</nav>
</div>